//! Reference Cloudflare Workers host for cfml-worker.
//!
//! Wires:
//! - `#[event(fetch)]` → [`cfml_worker::handle_fetch`]
//! - `#[event(scheduled)]` → [`cfml_worker::handle_scheduled`] (cron sweep
//!   of expired KV sessions → `onSessionEnd`)
//! - `#[durable_object] ApplicationScopeDO` → strong-consistency
//!   application-scope storage that
//!   [`cfml_worker::DoApplicationStore`] talks to via JSPI.
//!
//! Templates: copy this directory, edit `wrangler.toml` bindings, drop
//! your CFML under `cfml/`, deploy with `wrangler deploy`.

#![cfg(target_arch = "wasm32")]

use worker::*;

// Generated by build.rs from the cfml/ directory.
include!(concat!(env!("OUT_DIR"), "/embedded_files.rs"));

/// Virtual root the CFML VM sees as its filesystem root. Paths in
/// `CFML_FILES` are stored relative to this.
const VIRTUAL_ROOT: &str = "/app";

/// Name of the Application.cfc `this.name` we prime from the app store.
/// Keep in sync with the sample `cfml/Application.cfc`.
const APP_NAME: &str = "rustcfml-worker-demo";

fn build_config(env: &Env) -> cfml_worker::WorkerConfig {
    let mut config = cfml_worker::WorkerConfig::new(CFML_FILES, VIRTUAL_ROOT);
    config.app_names = vec![APP_NAME.to_string()];

    if let Ok(kv) = env.kv("SESSIONS") {
        config.kv_sessions = Some(kv);
    }
    if let Ok(kv) = env.kv("APP") {
        config.kv_application = Some(kv);
    }
    // DO wins over KV when present.
    if let Ok(ns) = env.durable_object("APP_DO") {
        config.do_application = Some(ns);
    }

    // D1 datasource registration is intentionally disabled. <cfquery>
    // via JSPI is wired but currently hangs on the Cloudflare runtime
    // because #[event(fetch)] (wasm-bindgen-futures) breaks the
    // contiguous-wasm-stack requirement of WebAssembly.promising.
    // Re-enable when the entry-point side is reworked.
    config
}

#[event(fetch)]
pub async fn fetch(req: Request, env: Env, ctx: Context) -> Result<Response> {
    let config = build_config(&env);
    cfml_worker::handle_fetch(req, env, ctx, &config).await
}

#[event(scheduled)]
pub async fn scheduled(event: ScheduledEvent, env: Env, ctx: ScheduleContext) {
    let config = build_config(&env);
    let _ = cfml_worker::handle_scheduled(event, env, ctx, &config).await;
}

/// Durable Object backing strong-consistency application scope.
///
/// One DO instance per `idFromName(<app_name>)` so the single-instance
/// request serialization gives atomic put-after-get for the contained
/// `(variables, started)` blob. The JSON shape matches
/// `cfml_worker::do_application_store::PersistedApp`.
#[durable_object]
pub struct ApplicationScopeDO {
    state: State,
}

impl DurableObject for ApplicationScopeDO {
    fn new(state: State, _env: Env) -> Self {
        Self { state }
    }

    async fn fetch(&self, mut req: Request) -> Result<Response> {
        let storage = self.state.storage();
        match (req.method(), req.path().as_str()) {
            (Method::Get, "/get") => match storage.get::<String>("body").await {
                Ok(Some(body)) => Response::ok(body),
                _ => Response::error("not found", 404),
            },
            (Method::Post, "/put") => {
                let body = req.text().await?;
                storage.put("body", body).await?;
                Ok(Response::empty()?.with_status(204))
            }
            _ => Response::error("not found", 404),
        }
    }
}
